//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: rideos/ride_hail_notification/v1/device.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Rideos_RideHailNotification_V1_DeviceRegistryServiceClient, then call methods of this protocol to make API calls.
public protocol Rideos_RideHailNotification_V1_DeviceRegistryServiceClientProtocol: GRPCClient {
  func setRiderDeviceInfo(
    _ request: Rideos_RideHailNotification_V1_SetRiderDeviceInfoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Rideos_RideHailNotification_V1_SetRiderDeviceInfoRequest, Rideos_RideHailNotification_V1_SetRiderDeviceInfoResponse>

  func setDriverDeviceInfo(
    _ request: Rideos_RideHailNotification_V1_SetDriverDeviceInfoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Rideos_RideHailNotification_V1_SetDriverDeviceInfoRequest, Rideos_RideHailNotification_V1_SetDriverDeviceInfoResponse>

}

extension Rideos_RideHailNotification_V1_DeviceRegistryServiceClientProtocol {

  /// Unary call to SetRiderDeviceInfo
  ///
  /// - Parameters:
  ///   - request: Request to send to SetRiderDeviceInfo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func setRiderDeviceInfo(
    _ request: Rideos_RideHailNotification_V1_SetRiderDeviceInfoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Rideos_RideHailNotification_V1_SetRiderDeviceInfoRequest, Rideos_RideHailNotification_V1_SetRiderDeviceInfoResponse> {
    return self.makeUnaryCall(
      path: "/rideos.ride_hail_notification.v1.DeviceRegistryService/SetRiderDeviceInfo",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to SetDriverDeviceInfo
  ///
  /// - Parameters:
  ///   - request: Request to send to SetDriverDeviceInfo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func setDriverDeviceInfo(
    _ request: Rideos_RideHailNotification_V1_SetDriverDeviceInfoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Rideos_RideHailNotification_V1_SetDriverDeviceInfoRequest, Rideos_RideHailNotification_V1_SetDriverDeviceInfoResponse> {
    return self.makeUnaryCall(
      path: "/rideos.ride_hail_notification.v1.DeviceRegistryService/SetDriverDeviceInfo",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

public final class Rideos_RideHailNotification_V1_DeviceRegistryServiceClient: Rideos_RideHailNotification_V1_DeviceRegistryServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the rideos.ride_hail_notification.v1.DeviceRegistryService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

