//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: rideos/ride_hail_notification/v1/notification.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Rideos_RideHailNotification_V1_RideHailNotificationServiceClient, then call methods of this protocol to make API calls.
public protocol Rideos_RideHailNotification_V1_RideHailNotificationServiceClientProtocol: GRPCClient {
  func pullNotifications(
    _ request: Rideos_RideHailNotification_V1_PullNotificationsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Rideos_RideHailNotification_V1_PullNotificationsRequest, Rideos_RideHailNotification_V1_PullNotificationsResponse>

  func ackNotifications(
    _ request: Rideos_RideHailNotification_V1_AckNotificationsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Rideos_RideHailNotification_V1_AckNotificationsRequest, Rideos_RideHailNotification_V1_AckNotificationsResponse>

}

extension Rideos_RideHailNotification_V1_RideHailNotificationServiceClientProtocol {

  /// Unary call to PullNotifications
  ///
  /// - Parameters:
  ///   - request: Request to send to PullNotifications.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func pullNotifications(
    _ request: Rideos_RideHailNotification_V1_PullNotificationsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Rideos_RideHailNotification_V1_PullNotificationsRequest, Rideos_RideHailNotification_V1_PullNotificationsResponse> {
    return self.makeUnaryCall(
      path: "/rideos.ride_hail_notification.v1.RideHailNotificationService/PullNotifications",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to AckNotifications
  ///
  /// - Parameters:
  ///   - request: Request to send to AckNotifications.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func ackNotifications(
    _ request: Rideos_RideHailNotification_V1_AckNotificationsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Rideos_RideHailNotification_V1_AckNotificationsRequest, Rideos_RideHailNotification_V1_AckNotificationsResponse> {
    return self.makeUnaryCall(
      path: "/rideos.ride_hail_notification.v1.RideHailNotificationService/AckNotifications",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

public final class Rideos_RideHailNotification_V1_RideHailNotificationServiceClient: Rideos_RideHailNotification_V1_RideHailNotificationServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the rideos.ride_hail_notification.v1.RideHailNotificationService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

